---
- name: Install Docker Compose Bash completion
  get_url:
    url: https://raw.githubusercontent.com/docker/compose/{{ 'master' if docker_compose_version == 'latest' else 'v'+docker_compose_version }}/contrib/completion/bash/docker-compose
    dest: /etc/bash_completion.d/docker-compose
    owner: root
    group: root
    mode: 0644
